# Auto-generated by IDE. All changes by user will be lost!
# Created at 11/02/13 2:14 AM

BASEDIR = $$_PRO_FILE_PWD_

INCLUDEPATH +=  \
    $$BASEDIR/src/api/client \
    $$BASEDIR/src/api/object/response \
    $$BASEDIR/src/api/object \
    $$BASEDIR/src/api/method \
    $$BASEDIR/src

SOURCES +=  \
    $$BASEDIR/src/YouMailBB10.cpp \
    $$BASEDIR/src/main.cpp

HEADERS +=  \
    $$BASEDIR/src/YouMailBB10.hpp \
    $$BASEDIR/src/api/client/apiclient.h \
    $$BASEDIR/src/api/method/AddFolder.h \
    $$BASEDIR/src/api/method/DeleteFolder.h \
    $$BASEDIR/src/api/method/GetAccessPoint.h \
    $$BASEDIR/src/api/method/GetFolders.h \
    $$BASEDIR/src/api/method/GetMessages.h \
    $$BASEDIR/src/api/method/GetPreferences.h \
    $$BASEDIR/src/api/method/GetSettings.h \
    $$BASEDIR/src/api/method/apimethod.h \
    $$BASEDIR/src/api/method/authenticate.h \
    $$BASEDIR/src/api/object/apiobject.h \
    $$BASEDIR/src/api/object/apiobjectserializer.h \
    $$BASEDIR/src/api/object/response/authtoken.h

CONFIG += precompile_header
PRECOMPILED_HEADER = $$BASEDIR/precompiled.h

lupdate_inclusion {
    SOURCES += \
        $$BASEDIR/../assets/*.qml
}

TRANSLATIONS = \
    $${TARGET}.ts

