#############################################################################
# Makefile for building: bbyoumail
# Generated by qmake (2.01a) (Qt 4.8.4) on: Thu Mar 7 00:28:43 2013
# Project:  bbyoumail.pro
# Template: app
# Command: c:/Users/Funbag/bb10ndk/host_10_0_9_404/win32/x86/usr/bin/qmake.exe -o Makefile bbyoumail.pro
#############################################################################

####### Compiler, tools and options

CC            = qcc -Vgcc_ntoarmv7le
CXX           = qcc -Vgcc_ntoarmv7le
DEFINES       = -DQT_NO_IMPORT_QT47_QML -DQ_OS_BLACKBERRY -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -Wno-psabi -fstack-protector-strong -mcpu=cortex-a9 -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -Wno-psabi -lang-c++ -fstack-protector-strong -mcpu=cortex-a9 -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/default -I. -I../../bb10ndk/target_10_0_9_1673/qnx6/usr/include/qt4/QtCore -I../../bb10ndk/target_10_0_9_1673/qnx6/usr/include/qt4/QtGui -I../../bb10ndk/target_10_0_9_1673/qnx6/usr/include/qt4 -I. -I. -I../../bb10ndk/target_10_0_9_1673/qnx6/usr/include -I../../bb10ndk/target_10_0_9_1673/qnx6/usr/include/freetype2
LINK          = qcc -Vgcc_ntoarmv7le
LFLAGS        = -lang-c++ -Wl,-rpath-link,C:/Users/Funbag/bb10ndk/target_10_0_9_1673/qnx6/armle-v7/lib -Wl,-rpath-link,C:/Users/Funbag/bb10ndk/target_10_0_9_1673/qnx6/armle-v7/usr/lib -Wl,-O1
LIBS          = $(SUBLIBS)  -LC:/Users/Funbag/bb10ndk/target_10_0_9_1673/qnx6/armle-v7/lib -LC:/Users/Funbag/bb10ndk/target_10_0_9_1673/qnx6/armle-v7/usr/lib -LC:/Users/Funbag/bb10ndk/target_10_0_9_1673/qnx6/armle-v7/usr/lib/qt4/lib -lQtGui -lQtCore -lm -lbps 
AR            = ntoarmv7-ar cqs
RANLIB        = ntoarmv7-ranlib
QMAKE         = c:/Users/Funbag/bb10ndk/host_10_0_9_404/win32/x86/usr/bin/qmake.exe
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = ntoarmv7-strip
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/YouMailBB10.cpp \
		src/api/client/apiclient.cpp \
		src/api/method/apimethodresponsehandler.cpp \
		src/api/object/apiobjectvisitor.cpp \
		src/api/object/response.cpp moc_YouMailBB10.cpp \
		moc_apiclient.cpp \
		moc_apimethodresponsehandler.cpp
OBJECTS       = main.o \
		YouMailBB10.o \
		apiclient.o \
		apimethodresponsehandler.o \
		apiobjectvisitor.o \
		response.o \
		moc_YouMailBB10.o \
		moc_apiclient.o \
		moc_apimethodresponsehandler.o
DIST          = ../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/common/g++-base.conf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/common/g++-unix.conf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/common/unix.conf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/common/qcc-base.conf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/common/qcc-base-qnx.conf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/qconfig.pri \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/qt_functions.prf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/qt_config.prf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/qnx-armv7le-qcc/qmake.conf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/default_pre.prf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/release.prf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/default_post.prf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/warn_on.prf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/qt.prf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/unix/thread.prf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/moc.prf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/resources.prf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/uic.prf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/yacc.prf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/lex.prf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		bbyoumail.pro
QMAKE_TARGET  = bbyoumail
DESTDIR       = 
TARGET        = bbyoumail

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: bbyoumail.pro  ../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/default/qmake.conf ../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/common/g++-base.conf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/common/g++-unix.conf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/common/unix.conf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/common/qcc-base.conf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/common/qcc-base-qnx.conf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/qconfig.pri \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/qt_functions.prf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/qt_config.prf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/qnx-armv7le-qcc/qmake.conf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/default_pre.prf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/release.prf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/default_post.prf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/warn_on.prf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/qt.prf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/unix/thread.prf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/moc.prf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/resources.prf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/uic.prf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/yacc.prf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/lex.prf \
		../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		c:\Users\Funbag\bb10ndk\target_10_0_9_1673\qnx6\armle-v7\usr\lib\qt4\lib\libQtGui.prl \
		c:\Users\Funbag\bb10ndk\target_10_0_9_1673\qnx6\armle-v7\usr\lib\qt4\lib\libQtCore.prl
	$(QMAKE) -o Makefile bbyoumail.pro
../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/common/g++-base.conf:
../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/common/g++-unix.conf:
../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/common/unix.conf:
../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/common/qcc-base.conf:
../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/common/qcc-base-qnx.conf:
../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/qconfig.pri:
../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/qt_functions.prf:
../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/qt_config.prf:
../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/qnx-armv7le-qcc/qmake.conf:
../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/default_pre.prf:
../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/release.prf:
../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/default_post.prf:
../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/warn_on.prf:
../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/qt.prf:
../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/unix/thread.prf:
../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/moc.prf:
../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/resources.prf:
../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/uic.prf:
../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/yacc.prf:
../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/lex.prf:
../../bb10ndk/target_10_0_9_1673/qnx6/usr/share/qt4/mkspecs/features/include_source_dir.prf:
c:\Users\Funbag\bb10ndk\target_10_0_9_1673\qnx6\armle-v7\usr\lib\qt4\lib\libQtGui.prl:
c:\Users\Funbag\bb10ndk\target_10_0_9_1673\qnx6\armle-v7\usr\lib\qt4\lib\libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile bbyoumail.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/bbyoumail1.0.0 || $(MKDIR) .tmp/bbyoumail1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/bbyoumail1.0.0/ && $(COPY_FILE) --parents precompiled.h src/YouMailBB10.hpp src/api/constants.h src/api/client/apiclient.h src/api/method/AddFolder.h src/api/method/apimethod.h src/api/method/apimethodresponsehandler.h src/api/method/apimethodvisitor.h src/api/method/authenticate.h src/api/method/DeleteFolder.h src/api/method/GetAccessPoint.h src/api/method/GetFolders.h src/api/method/GetMessages.h src/api/method/GetPreferences.h src/api/method/GetSettings.h src/api/object/alertsettings.h src/api/object/apiobject.h src/api/object/apiobjectdeserializer.h src/api/object/apiobjectserializer.h src/api/object/apiobjectvisitor.h src/api/object/apiobjectvisitorfactory.h src/api/object/authtoken.h src/api/object/contact.h src/api/object/messageboxentry.h src/api/object/messageboxfolder.h src/api/object/preferences.h src/api/object/pushregistration.h src/api/object/response.h src/api/object/settings.h src/api/object/transcriptionsettings.h src/api/util/util.h .tmp/bbyoumail1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/YouMailBB10.cpp src/api/client/apiclient.cpp src/api/method/apimethodresponsehandler.cpp src/api/object/apiobjectvisitor.cpp src/api/object/response.cpp .tmp/bbyoumail1.0.0/ && $(COPY_FILE) --parents translations\YouMailBB10.ts .tmp/bbyoumail1.0.0/ && (cd `dirname .tmp/bbyoumail1.0.0` && $(TAR) bbyoumail1.0.0.tar bbyoumail1.0.0 && $(COMPRESS) bbyoumail1.0.0.tar) && $(MOVE) `dirname .tmp/bbyoumail1.0.0`/bbyoumail1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/bbyoumail1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_YouMailBB10.cpp moc_apiclient.cpp moc_apimethodresponsehandler.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_YouMailBB10.cpp moc_apiclient.cpp moc_apimethodresponsehandler.cpp
moc_YouMailBB10.cpp: src/api/client/apiclient.h \
		src/api/method/apimethod.h \
		src/api/object/apiobject.h \
		src/api/object/apiobjectvisitor.h \
		src/api/method/authenticate.h \
		src/api/object/authtoken.h \
		src/api/object/apiobjectvisitorfactory.h \
		src/api/object/apiobjectdeserializer.h \
		src/api/object/transcriptionsettings.h \
		src/api/constants.h \
		src/api/object/alertsettings.h \
		src/api/object/pushregistration.h \
		src/api/object/settings.h \
		src/api/object/messageboxfolder.h \
		src/api/object/messageboxentry.h \
		src/api/object/preferences.h \
		src/api/object/response.h \
		src/api/util/util.h \
		src/api/object/apiobjectserializer.h \
		src/YouMailBB10.hpp
	C:/Users/Funbag/bb10ndk/host_10_0_9_404/win32/x86/usr/bin/moc.exe $(DEFINES) $(INCPATH) -D__QNXNTO__ src/YouMailBB10.hpp -o moc_YouMailBB10.cpp

moc_apiclient.cpp: src/api/method/apimethod.h \
		src/api/object/apiobject.h \
		src/api/object/apiobjectvisitor.h \
		src/api/method/authenticate.h \
		src/api/object/authtoken.h \
		src/api/object/apiobjectvisitorfactory.h \
		src/api/object/apiobjectdeserializer.h \
		src/api/object/transcriptionsettings.h \
		src/api/constants.h \
		src/api/object/alertsettings.h \
		src/api/object/pushregistration.h \
		src/api/object/settings.h \
		src/api/object/messageboxfolder.h \
		src/api/object/messageboxentry.h \
		src/api/object/preferences.h \
		src/api/object/response.h \
		src/api/util/util.h \
		src/api/object/apiobjectserializer.h \
		src/api/client/apiclient.h
	C:/Users/Funbag/bb10ndk/host_10_0_9_404/win32/x86/usr/bin/moc.exe $(DEFINES) $(INCPATH) -D__QNXNTO__ src/api/client/apiclient.h -o moc_apiclient.cpp

moc_apimethodresponsehandler.cpp: src/api/method/apimethodvisitor.h \
		src/api/method/apimethodresponsehandler.h
	C:/Users/Funbag/bb10ndk/host_10_0_9_404/win32/x86/usr/bin/moc.exe $(DEFINES) $(INCPATH) -D__QNXNTO__ src/api/method/apimethodresponsehandler.h -o moc_apimethodresponsehandler.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: src/main.cpp src\YouMailBB10.hpp \
		src\api\client\apiclient.h \
		src\api\method\apimethod.h \
		src\api\object\apiobject.h \
		src\api\object\apiobjectvisitor.h \
		src\api\method\authenticate.h \
		src\api\object\authtoken.h \
		src\api\object\apiobjectvisitorfactory.h \
		src\api\object\apiobjectdeserializer.h \
		src\api\object\transcriptionsettings.h \
		src\api\constants.h \
		src\api\object\alertsettings.h \
		src\api\object\pushregistration.h \
		src\api\object\settings.h \
		src\api\object\messageboxfolder.h \
		src\api\object\messageboxentry.h \
		src\api\object\preferences.h \
		src\api\object\response.h \
		src\api\util\util.h \
		src\api\object\apiobjectserializer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

YouMailBB10.o: src/YouMailBB10.cpp src\YouMailBB10.hpp \
		src\api\client\apiclient.h \
		src\api\method\apimethod.h \
		src\api\object\apiobject.h \
		src\api\object\apiobjectvisitor.h \
		src\api\method\authenticate.h \
		src\api\object\authtoken.h \
		src\api\object\apiobjectvisitorfactory.h \
		src\api\object\apiobjectdeserializer.h \
		src\api\object\transcriptionsettings.h \
		src\api\constants.h \
		src\api\object\alertsettings.h \
		src\api\object\pushregistration.h \
		src\api\object\settings.h \
		src\api\object\messageboxfolder.h \
		src\api\object\messageboxentry.h \
		src\api\object\preferences.h \
		src\api\object\response.h \
		src\api\util\util.h \
		src\api\object\apiobjectserializer.h \
		src\api\method\apimethodresponsehandler.h \
		src\api\method\apimethodvisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o YouMailBB10.o src/YouMailBB10.cpp

apiclient.o: src/api/client/apiclient.cpp src\api\client\apiclient.h \
		src\api\method\apimethod.h \
		src\api\object\apiobject.h \
		src\api\object\apiobjectvisitor.h \
		src\api\method\authenticate.h \
		src\api\object\authtoken.h \
		src\api\object\apiobjectvisitorfactory.h \
		src\api\object\apiobjectdeserializer.h \
		src\api\object\transcriptionsettings.h \
		src\api\constants.h \
		src\api\object\alertsettings.h \
		src\api\object\pushregistration.h \
		src\api\object\settings.h \
		src\api\object\messageboxfolder.h \
		src\api\object\messageboxentry.h \
		src\api\object\preferences.h \
		src\api\object\response.h \
		src\api\util\util.h \
		src\api\object\apiobjectserializer.h \
		src\api\method\apimethodresponsehandler.h \
		src\api\method\apimethodvisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o apiclient.o src/api/client/apiclient.cpp

apimethodresponsehandler.o: src/api/method/apimethodresponsehandler.cpp src\api\method\apimethodresponsehandler.h \
		src\api\method\apimethodvisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o apimethodresponsehandler.o src/api/method/apimethodresponsehandler.cpp

apiobjectvisitor.o: src/api/object/apiobjectvisitor.cpp src\api\object\apiobjectvisitor.h \
		src\api\object\apiobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o apiobjectvisitor.o src/api/object/apiobjectvisitor.cpp

response.o: src/api/object/response.cpp src\api\object\response.h \
		src\api\object\apiobject.h \
		src\api\object\apiobjectvisitor.h \
		src\api\constants.h \
		src\api\object\messageboxentry.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o response.o src/api/object/response.cpp

moc_YouMailBB10.o: moc_YouMailBB10.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_YouMailBB10.o moc_YouMailBB10.cpp

moc_apiclient.o: moc_apiclient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_apiclient.o moc_apiclient.cpp

moc_apimethodresponsehandler.o: moc_apimethodresponsehandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_apimethodresponsehandler.o moc_apimethodresponsehandler.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

